Add Vision
team4099/DeepSpace-2019 pull request #13
Opened 2019-01-23 22:24 UTC by rbhog

Resolves #11

2019-01-23 23:08 UTC, atzho requested changes

2019-01-23 23:08 UTC, atzho commented on src/main/kotlin/org/usfirst/frc/team4099/robot/Robot.kt
> -            if (intake.up && controlboard.lowerIntake) {
Why did you get rid of this

2019-01-23 23:08 UTC, azhong2002 commented on src/main/kotlin/org/usfirst/frc/team4099/robot/subsystems/Superstructure.kt
> +                SystemState.INTAKE_UP -> handleElevatorUp()
This should move the intake up, not the elevator

2019-01-24 00:39 UTC, ktorsh reviewed
Should note that these need to be changes (the constants) most likely if you copied from last year

2019-01-24 00:46 UTC, ktorsh commented on src/main/kotlin/org/usfirst/frc/team4099/robot/subsystems/Elevator.kt
> +        talon.set(ControlMode.Velocity, -inchesPerSecond)
Is there a specific reason this is set to negative. If it should be negative, you should invert the talon rather than doing this.

2019-01-24 00:46 UTC, ktorsh requested changes
Needs some work, but is done fairly well for the most part

2019-01-24 00:51 UTC, ktorsh commented on src/main/kotlin/org/usfirst/frc/team4099/robot/subsystems/Elevator.kt
> +    enum class ElevatorState (val targetPos : Double) {
Idk if you want to add this, but perhaps have a state when the elevator is completely down, as we may not want to have the elevator raised at all during certain times (ex. when climbing)

2019-01-24 00:52 UTC, ktorsh commented on src/main/kotlin/org/usfirst/frc/team4099/robot/subsystems/Elevator.kt
> +            elevatorState = ElevatorState.HATCHLOW
should be zero in my opinion,so set it to a height of 0 or open loop.

2019-01-24 00:52 UTC, ktorsh commented on src/main/kotlin/org/usfirst/frc/team4099/robot/subsystems/Elevator.kt
> +                elevatorPower = -talon.motorOutputPercent
again might want to invert the talon instead of doing this

2019-01-24 02:14 UTC, merged